const robots = [
    {
        "id":"100001",
        "titulo": "Superman",
        "vol": "1",
        "desc":"La historia sigue a Clark Kent, un periodista en el Daily Planet de Metrópolis, que lleva una doble vida como el superhéroe",
        "image":"../asset/img/Productos/Superman-Tomo1.jpg",
        "price":"15000",
        "stock":"10",
        "editorial":"Polis Metro",
    },
    {
        "id":"100002",
        "titulo": "Batman",
        "vol": "1",
        "desc":"La historia sigue a Bruce Wayne, un multimillonario que lucha contra el crimen en Gotham City como el justiciero enmascarado",
        "image":"../asset/img/Productos/Batman-Tomo1.jpg",
        "price":"16990",
        "stock":"5",
        "editorial":"Tic Go",
    },
    {
        "id":"100003",
        "titulo": "Flash",
        "vol": "1",
        "desc":"La historia trata de Barry Allen, un científico forense que adquiere la capacidad de moverse a velocidades extremas",
        "image":"../asset/img/Productos/Flash-Tomo1.jpg",
        "price":"15990",
        "stock":"14",
        "editorial":"Tralcen",
    },
    {
        "id":"100004",
        "titulo": "Wonder Woman",
        "vol": "1",
        "desc":"La historia sigue a Diana, una guerrera amazona de Themyscira, que decide intervenir en los asuntos de la humanidad",
        "image":"../asset/img/Productos/WonderWoman-Tomo1.jpg",
        "price":"17990",
        "stock":"8",
        "editorial":"Cira Mysthe",
    },
    {
        "id":"100005",
        "titulo": "Shazam",
        "vol": "1",
        "desc":"La historia trata de Billy Batson, un adolescente que recibe poderes mágicos de un antiguo mago, lo que le permite transformarse en un antiguo guerrero",
        "image":"../asset/img/Productos/Shazam-Tomo1.jpg",
        "price":"18990",
        "stock":"20",
        "editorial":"Sonllybi",
    },
    {
        "id":"100006",
        "titulo": "Black Adam",
        "vol": "1",
        "desc":"La historia sigue a Teth-Adam, un antiguo guerrero egipcio que recibe poderes sobrenaturales de los dioses y se convierte en un poderoso enemigo",
        "image":"../asset/img/Productos/BlackAdam-Tomo1.jpg",
        "price":"16990",
        "stock":"20",
        "editorial":"Sonllybi",
    },
    {
        "id":"100007",
        "titulo": "Linterna Verde",
        "vol": "1",
        "desc":"La historia sigue a Hal Jordan, un piloto de pruebas que se une a los Linterna Verde, un cuerpo intergaláctico",
        "image":"../asset/img/Productos/Superman-Tomo1.jpg",
        "price":"15990",
        "stock":"13",
        "editorial":"Danjor",
    },
    {
        "id":"100008",
        "titulo": "Spiderman",
        "vol": "1",
        "desc":"La historia sigue a Peter Parker, un estudiante de secundaria que adquiere habilidades arácnidas extraordinarias",
        "image":"../asset/img/Productos/Superman-Tomo1.jpg",
        "price":"19990",
        "stock":"9",
        "editorial":"Klynbroo",
    },
    {
        "id":"100009",
        "titulo": "Ironman",
        "vol": "1",
        "desc":"La historia sigue a Tony Stark, un multimillonario empresario e inventor que, tras ser secuestrado y casi morir",
        "image":"../asset/img/Productos/Superman-Tomo1.jpg",
        "price":"14990",
        "stock":"5",
        "editorial":"Yorknew",
    },
    {
        "id":"100010",
        "titulo": "Thor",
        "vol": "1",
        "desc":"La historia sigue a Thor, el dios nórdico del trueno, que es desterrado a la Tierra por su arrogancia y comportamiento impulsivo",
        "image":"../asset/img/Productos/Superman-Tomo1.jpg",
        "price":"17990",
        "stock":"10",
        "editorial":"Gardas",
    },
    {
        "id":"100011",
        "titulo": "Deadpool",
        "vol": "1",
        "desc":"La historia sigue a Wade Wilson, un exsoldado de élite convertido en mercenario que se somete a un experimento fallido",
        "image":"../asset/img/Productos/Superman-Tomo1.jpg",
        "price":"16990",
        "stock":"1",
        "editorial":"Forcex",
    },
    {
        "id":"100012",
        "titulo": "Hulk",
        "vol": "1",
        "desc":"La historia sigue a Bruce Banner, un científico que se transforma en la criatura verde Hulk tras un accidente con radiación",
        "image":"../asset/img/Productos/Superman-Tomo1.jpg",
        "price":"11990",
        "stock":"12",
        "editorial":"Maga",
    },
];

module.exports = {
    robots
}